# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6b0b6ad1680a0f05b340ea4383d04c756248225144b8db8f1585cdd38cbbd672c4aca8254e99079ecec0dbe4f42a343c4e89538af7caaa4bf8a7b92934ebdf8

test:
  secret_key_base: fb60c5e31c1d33a703826cf5185820ef85f5c3a6369583e8c54ec3ccebaa8ebf1bba09f57a9e267e1d8cdc0bbbc857d39836c0124c29474bb9e71d040cb84c87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
